### PR TITLE
Fix dxy error

### PR DESCRIPTION
**Pull request by tlatorre-uchicago**
Trying to find everywhere in the ntuplizer where the dxyerror is used. Did I miss anywhere else? Haven't even compile tested this yet, so don't merge.

### CODE REVIEW

**Comment by tlatorre-uchicago** [comment]
ok, it at least compiles now

**Comment by ocerri** [comment]
Is it still in the "don't merge" status?

**Comment by tlatorre-uchicago** [comment]
Yeah, I still haven't tested it. Still waiting for the previous jobs to finish. Will try and test it out after that

**Comment by tlatorre-uchicago** [comment]
I've tested it out on a few files. It seems to have a non-negligible effect, but nothing big. I think it's probably ok to merge.

**Pull request merged**
